package com.sunny.code;

public enum Action {
    FIND_CHILD_ALL, FIND_CHILD_BYNAME, ADD_CHILD, UPDATE_CHILD_CLASS, FIND_CHILD_ALLWITHRIDE,
    FIND_CHILD_BYID, FIND_CHILD_BYBIRTHMONTH, FIND_CHILD_BYCLASSANDNAME, FIND_CHILD_ATTENDING,
    UPDATE_CHILD, DELETE_CHILD, CREATE_CHILD_WITHEXCEL, FIND_USER_ALL, FIND_USER_BYID, CREATE_USER,
    UPDATE_USER, DELETE_USER, FIND_RIDE, FIND_RIDE_BYID, FIND_CLASS_ALL, FIND_CLASS_BYID, CREATE_CLASS,
    UPDATE_CLASS, DELETE_CLASS, DELETE_CLASS_BYID, FIND_PARENTS_ALL, FIND_PARENTS_BYID, ADD_PARENTS,
    UPDATE_PARENTS, DELETE_PARENTS, DELETE_PARENTS_BYID, FIND_PARENTS_BYNAME, UPDATE_MEETINGLOCATION,
    CREATE_MEETINGLOCATION, DELETE_MEETINGLOCATION_BYID;

}
